dist: bionic

language: bash

services:
  - docker

script:
  - docker login -u="$registryuser" -p="$registrypw"
  - docker build -t apollo-server .
  - docker tag apollo-server flotte-docker-registry.spdns.org/flotte_user-managment
  - docker push apollo-server:latest